import type { AIResearchLab } from '@/types';

// Academic AI research institutions, AI safety organizations, and major research labs
// Focused on frontier AI research, safety, and academic contributions

export const AI_RESEARCH_LABS: AIResearchLab[] = [
  // AI Safety & Alignment Organizations
  {
    id: 'anthropic-research',
    name: 'Anthropic',
    type: 'industry',
    city: 'San Francisco',
    country: 'United States',
    lat: 37.7937,
    lon: -122.3965,
    foundedYear: 2021,
    focusAreas: ['AI Safety', 'Constitutional AI', 'Large Language Models', 'Interpretability'],
    notableWork: ['Claude AI family', 'Constitutional AI framework', 'Mechanistic interpretability'],
    publications: 45,
  },
  {
    id: 'openai-research',
    name: 'OpenAI',
    type: 'industry',
    city: 'San Francisco',
    country: 'United States',
    lat: 37.7562,
    lon: -122.4193,
    foundedYear: 2015,
    focusAreas: ['AGI', 'Large Language Models', 'Reinforcement Learning', 'AI Safety'],
    notableWork: ['GPT-4', 'DALL-E', 'CLIP', 'Whisper'],
    publications: 150,
  },
  {
    id: 'deepmind',
    name: 'Google DeepMind',
    type: 'industry',
    city: 'London',
    country: 'United Kingdom',
    lat: 51.5310,
    lon: -0.1247,
    foundedYear: 2010,
    focusAreas: ['Reinforcement Learning', 'Protein Folding', 'Game AI', 'Multimodal AI'],
    notableWork: ['AlphaGo', 'AlphaFold', 'Gemini', 'MuZero'],
    publications: 500,
  },
  {
    id: 'meta-fair',
    name: 'Meta AI (FAIR)',
    type: 'industry',
    city: 'Menlo Park',
    country: 'United States',
    lat: 37.4848,
    lon: -122.1482,
    foundedYear: 2013,
    focusAreas: ['Computer Vision', 'NLP', 'Open Source AI', 'Reinforcement Learning'],
    notableWork: ['Llama', 'PyTorch', 'SAM', 'DINOv2'],
    publications: 800,
  },
  {
    id: 'microsoft-research',
    name: 'Microsoft Research AI',
    type: 'industry',
    city: 'Redmond',
    country: 'United States',
    lat: 47.6423,
    lon: -122.1390,
    foundedYear: 1991,
    focusAreas: ['Deep Learning', 'NLP', 'Responsible AI', 'Quantum Computing'],
    notableWork: ['ResNet', 'Azure AI', 'Phi models', 'Turing-NLG'],
    publications: 1200,
  },

  // University Research Labs - United States
  {
    id: 'stanford-hai',
    name: 'Stanford HAI',
    type: 'academic',
    city: 'Stanford',
    country: 'United States',
    lat: 37.4275,
    lon: -122.1697,
    foundedYear: 2019,
    focusAreas: ['Human-Centered AI', 'AI Ethics', 'AI Policy', 'Interdisciplinary Research'],
    notableWork: ['AI Index Report', 'Foundation Models Research'],
    publications: 300,
    faculty: 200,
  },
  {
    id: 'mit-csail',
    name: 'MIT CSAIL',
    type: 'academic',
    city: 'Cambridge',
    country: 'United States',
    lat: 42.3601,
    lon: -71.0942,
    foundedYear: 1963,
    focusAreas: ['Computer Vision', 'Robotics', 'NLP', 'Machine Learning Theory'],
    notableWork: ['Object detection', 'Neural architecture search', 'Federated learning'],
    publications: 2000,
    faculty: 80,
  },
  {
    id: 'berkeley-ai',
    name: 'UC Berkeley AI Research (BAIR)',
    type: 'academic',
    city: 'Berkeley',
    country: 'United States',
    lat: 37.8719,
    lon: -122.2585,
    foundedYear: 2016,
    focusAreas: ['Deep Learning', 'Robotics', 'Computer Vision', 'NLP'],
    notableWork: ['Deep RL', 'Neural Networks', 'Autonomous Systems'],
    publications: 450,
    faculty: 50,
  },
  {
    id: 'cmu-ml',
    name: 'CMU Machine Learning Department',
    type: 'academic',
    city: 'Pittsburgh',
    country: 'United States',
    lat: 40.4433,
    lon: -79.9436,
    foundedYear: 2006,
    focusAreas: ['Machine Learning Theory', 'Deep Learning', 'Statistical ML', 'Neural Computation'],
    notableWork: ['Statistical learning', 'Graph neural networks', 'Meta-learning'],
    publications: 800,
    faculty: 45,
  },
  {
    id: 'princeton-ai',
    name: 'Princeton AI',
    type: 'academic',
    city: 'Princeton',
    country: 'United States',
    lat: 40.3430,
    lon: -74.6514,
    foundedYear: 1985,
    focusAreas: ['Computer Vision', 'ML Theory', 'NLP', 'AI Safety'],
    notableWork: ['ImageNet', 'Object recognition', 'Neural networks'],
    publications: 400,
    faculty: 30,
  },

  // University Research Labs - Europe
  {
    id: 'oxford-ai',
    name: 'Oxford AI',
    type: 'academic',
    city: 'Oxford',
    country: 'United Kingdom',
    lat: 51.7548,
    lon: -1.2544,
    foundedYear: 1985,
    focusAreas: ['Deep Learning', 'Computer Vision', 'NLP', 'Healthcare AI'],
    notableWork: ['Visual Geometry Group', 'Deep learning for healthcare'],
    publications: 600,
    faculty: 40,
  },
  {
    id: 'cambridge-ml',
    name: 'Cambridge Machine Learning Group',
    type: 'academic',
    city: 'Cambridge',
    country: 'United Kingdom',
    lat: 52.2043,
    lon: 0.1218,
    foundedYear: 1990,
    focusAreas: ['Bayesian ML', 'Probabilistic Models', 'Deep Learning', 'Reinforcement Learning'],
    notableWork: ['Gaussian processes', 'Bayesian optimization', 'Probabilistic programming'],
    publications: 500,
    faculty: 35,
  },
  {
    id: 'eth-ai',
    name: 'ETH Zurich AI Center',
    type: 'academic',
    city: 'Zurich',
    country: 'Switzerland',
    lat: 47.3769,
    lon: 8.5417,
    foundedYear: 2020,
    focusAreas: ['Computer Vision', 'Robotics', 'ML Theory', 'Trustworthy AI'],
    notableWork: ['3D vision', 'Autonomous systems', 'Safe AI'],
    publications: 350,
    faculty: 60,
  },
  {
    id: 'mpi-is',
    name: 'Max Planck Institute for Intelligent Systems',
    type: 'research institute',
    city: 'Tübingen',
    country: 'Germany',
    lat: 48.5216,
    lon: 9.0576,
    foundedYear: 2011,
    focusAreas: ['Machine Learning', 'Computer Vision', 'Robotics', 'Causal Inference'],
    notableWork: ['Causal ML', 'Embodied AI', 'Vision research'],
    publications: 400,
    faculty: 25,
  },

  // University Research Labs - Asia
  {
    id: 'tsinghua-ai',
    name: 'Tsinghua University AI Institute',
    type: 'academic',
    city: 'Beijing',
    country: 'China',
    lat: 39.9994,
    lon: 116.3267,
    foundedYear: 2018,
    focusAreas: ['Computer Vision', 'NLP', 'Robotics', 'AI Safety'],
    notableWork: ['Large-scale AI models', 'Vision research'],
    publications: 700,
    faculty: 100,
  },
  {
    id: 'peking-ai',
    name: 'Peking University AI',
    type: 'academic',
    city: 'Beijing',
    country: 'China',
    lat: 39.9925,
    lon: 116.3059,
    foundedYear: 2002,
    focusAreas: ['NLP', 'Knowledge Graphs', 'Computer Vision', 'ML Theory'],
    notableWork: ['Chinese NLP', 'Knowledge representation'],
    publications: 600,
    faculty: 80,
  },
  {
    id: 'tokyo-ai',
    name: 'University of Tokyo AI Research',
    type: 'academic',
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.7130,
    lon: 139.7625,
    foundedYear: 2020,
    focusAreas: ['Robotics', 'Computer Vision', 'Human-AI Interaction', 'Healthcare AI'],
    notableWork: ['Humanoid robotics', 'Medical AI'],
    publications: 400,
    faculty: 50,
  },
  {
    id: 'nus-ai',
    name: 'National University of Singapore AI',
    type: 'academic',
    city: 'Singapore',
    country: 'Singapore',
    lat: 1.2966,
    lon: 103.7764,
    foundedYear: 2018,
    focusAreas: ['Computer Vision', 'NLP', 'Healthcare AI', 'Trustworthy AI'],
    notableWork: ['Medical imaging', 'Southeast Asia NLP'],
    publications: 350,
    faculty: 45,
  },

  // AI Safety & Governance Organizations
  {
    id: 'chai-berkeley',
    name: 'Center for Human-Compatible AI (CHAI)',
    type: 'research institute',
    city: 'Berkeley',
    country: 'United States',
    lat: 37.8719,
    lon: -122.2585,
    foundedYear: 2016,
    focusAreas: ['AI Safety', 'Value Alignment', 'Inverse Reinforcement Learning', 'AI Governance'],
    notableWork: ['Value alignment research', 'Cooperative inverse RL'],
    publications: 120,
    faculty: 15,
  },
  {
    id: 'miri',
    name: 'Machine Intelligence Research Institute (MIRI)',
    type: 'research institute',
    city: 'Berkeley',
    country: 'United States',
    lat: 37.8715,
    lon: -122.2730,
    foundedYear: 2000,
    focusAreas: ['AI Safety', 'Formal Verification', 'Decision Theory', 'Agent Foundations'],
    notableWork: ['Agent foundations', 'Alignment theory'],
    publications: 80,
  },
  {
    id: 'fhi',
    name: 'Future of Humanity Institute',
    type: 'research institute',
    city: 'Oxford',
    country: 'United Kingdom',
    lat: 51.7548,
    lon: -1.2544,
    foundedYear: 2005,
    focusAreas: ['Existential Risk', 'AI Governance', 'Long-term AI Safety', 'Ethics'],
    notableWork: ['AI risk research', 'Global catastrophic risks'],
    publications: 200,
    faculty: 20,
  },
  {
    id: 'alignment-research-center',
    name: 'Alignment Research Center (ARC)',
    type: 'research institute',
    city: 'Berkeley',
    country: 'United States',
    lat: 37.8715,
    lon: -122.2730,
    foundedYear: 2021,
    focusAreas: ['AI Alignment', 'Eliciting Latent Knowledge', 'AI Safety Evaluations'],
    notableWork: ['ARC Evals', 'ELK research'],
    publications: 30,
  },

  // Industry Research Labs - Asia
  {
    id: 'baidu-research',
    name: 'Baidu Research',
    type: 'industry',
    city: 'Beijing',
    country: 'China',
    lat: 39.9925,
    lon: 116.3272,
    foundedYear: 2013,
    focusAreas: ['NLP', 'Computer Vision', 'Speech Recognition', 'Autonomous Driving'],
    notableWork: ['ERNIE models', 'Apollo autonomous driving', 'PaddlePaddle'],
    publications: 400,
  },
  {
    id: 'alibaba-damo',
    name: 'Alibaba DAMO Academy',
    type: 'industry',
    city: 'Hangzhou',
    country: 'China',
    lat: 30.2741,
    lon: 120.1551,
    foundedYear: 2017,
    focusAreas: ['NLP', 'Computer Vision', 'Speech', 'Quantum Computing'],
    notableWork: ['Qwen models', 'Vision transformers', 'Cloud AI'],
    publications: 300,
  },
  {
    id: 'sony-ai',
    name: 'Sony AI',
    type: 'industry',
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.6586,
    lon: 139.7454,
    foundedYear: 2019,
    focusAreas: ['Gaming AI', 'Computer Vision', 'Robotics', 'Creativity AI'],
    notableWork: ['Gran Turismo AI', 'Gastronomy AI'],
    publications: 80,
  },

  // Specialized Research Centers
  {
    id: 'allen-ai',
    name: 'Allen Institute for AI (AI2)',
    type: 'research institute',
    city: 'Seattle',
    country: 'United States',
    lat: 47.6205,
    lon: -122.3493,
    foundedYear: 2014,
    focusAreas: ['NLP', 'Computer Vision', 'Reasoning', 'Open Research'],
    notableWork: ['Semantic Scholar', 'AllenNLP', 'OLMo'],
    publications: 500,
  },
  {
    id: 'ibm-research-ai',
    name: 'IBM Research AI',
    type: 'industry',
    city: 'Yorktown Heights',
    country: 'United States',
    lat: 41.2788,
    lon: -73.8084,
    foundedYear: 1945,
    focusAreas: ['Enterprise AI', 'Quantum AI', 'Trustworthy AI', 'NLP'],
    notableWork: ['Watson', 'Granite models', 'Neuro-symbolic AI'],
    publications: 1000,
  },
  {
    id: 'mila',
    name: 'Mila - Quebec AI Institute',
    type: 'research institute',
    city: 'Montreal',
    country: 'Canada',
    lat: 45.5017,
    lon: -73.5673,
    foundedYear: 1993,
    focusAreas: ['Deep Learning', 'Reinforcement Learning', 'NLP', 'Climate AI'],
    notableWork: ['GANs', 'Attention mechanisms', 'Graph neural networks'],
    publications: 800,
    faculty: 70,
  },
  {
    id: 'vector-institute',
    name: 'Vector Institute',
    type: 'research institute',
    city: 'Toronto',
    country: 'Canada',
    lat: 43.6532,
    lon: -79.3832,
    foundedYear: 2017,
    focusAreas: ['Deep Learning', 'Healthcare AI', 'ML Theory', 'Responsible AI'],
    notableWork: ['Medical AI', 'Vector scholarship program'],
    publications: 250,
    faculty: 40,
  },

  // European Industry Labs
  {
    id: 'huawei-paris',
    name: 'Huawei Paris Research Center',
    type: 'industry',
    city: 'Paris',
    country: 'France',
    lat: 48.8566,
    lon: 2.3522,
    foundedYear: 2016,
    focusAreas: ['Computer Vision', 'NLP', 'Mathematics', 'Theory'],
    notableWork: ['Vision research', 'Theoretical ML'],
    publications: 200,
  },
  {
    id: 'samsung-ai',
    name: 'Samsung AI Center',
    type: 'industry',
    city: 'Cambridge',
    country: 'United Kingdom',
    lat: 52.2043,
    lon: 0.1218,
    foundedYear: 2018,
    focusAreas: ['Computer Vision', 'On-Device AI', 'Generative AI', 'Robotics'],
    notableWork: ['Mobile AI', 'Edge computing'],
    publications: 150,
  },
];
