import type { StartupEcosystem } from '@/types';

// Global startup and VC ecosystems focused on tech/AI
// Data includes venture capital activity, startup density, and funding

export const STARTUP_ECOSYSTEMS: StartupEcosystem[] = [
  // Silicon Valley / Bay Area
  {
    id: 'sf-bay-area',
    name: 'San Francisco Bay Area',
    city: 'San Francisco',
    country: 'United States',
    lat: 37.7749,
    lon: -122.4194,
    ecosystemTier: 'tier1',
    totalFunding2024: 62000000000, // $62B
    activeStartups: 12500,
    unicorns: 78,
    topSectors: ['AI/ML', 'Enterprise SaaS', 'Fintech', 'Biotech'],
    majorVCs: ['Sequoia Capital', 'Andreessen Horowitz', 'Accel', 'Kleiner Perkins', 'Greylock'],
    notableStartups: ['OpenAI', 'Anthropic', 'Scale AI', 'Databricks', 'Stripe'],
    avgSeedRound: 3500000,
    avgSeriesA: 18000000,
  },
  {
    id: 'palo-alto',
    name: 'Palo Alto / Stanford',
    city: 'Palo Alto',
    country: 'United States',
    lat: 37.4419,
    lon: -122.1430,
    ecosystemTier: 'tier1',
    totalFunding2024: 28000000000,
    activeStartups: 4200,
    unicorns: 45,
    topSectors: ['AI/ML', 'Enterprise Software', 'Semiconductors', 'Cleantech'],
    majorVCs: ['Y Combinator', 'NEA', 'Lightspeed', 'Khosla Ventures'],
    notableStartups: ['Adept AI', 'Inflection AI', 'SambaNova', 'Palantir'],
    avgSeedRound: 4000000,
    avgSeriesA: 20000000,
  },

  // Other US Tech Hubs
  {
    id: 'nyc',
    name: 'New York City',
    city: 'New York',
    country: 'United States',
    lat: 40.7128,
    lon: -74.0060,
    ecosystemTier: 'tier1',
    totalFunding2024: 35000000000,
    activeStartups: 9000,
    unicorns: 42,
    topSectors: ['Fintech', 'Enterprise SaaS', 'AI/ML', 'Media/Adtech'],
    majorVCs: ['Union Square Ventures', 'Lerer Hippeau', 'FirstMark', 'Insight Partners'],
    notableStartups: ['Hugging Face', 'DataBricks NYC', 'Verkada', 'Toast'],
    avgSeedRound: 2800000,
    avgSeriesA: 15000000,
  },
  {
    id: 'boston',
    name: 'Boston',
    city: 'Boston',
    country: 'United States',
    lat: 42.3601,
    lon: -71.0589,
    ecosystemTier: 'tier2',
    totalFunding2024: 18000000000,
    activeStartups: 4500,
    unicorns: 28,
    topSectors: ['Biotech', 'Robotics', 'AI/ML', 'Healthcare IT'],
    majorVCs: ['General Catalyst', 'Battery Ventures', 'Atlas Venture', 'Highland Capital'],
    notableStartups: ['Boston Dynamics', 'DataRobot', 'Toast', 'Optimus Ride'],
    avgSeedRound: 2500000,
    avgSeriesA: 12000000,
  },
  {
    id: 'seattle',
    name: 'Seattle',
    city: 'Seattle',
    country: 'United States',
    lat: 47.6062,
    lon: -122.3321,
    ecosystemTier: 'tier2',
    totalFunding2024: 12000000000,
    activeStartups: 3800,
    unicorns: 22,
    topSectors: ['Cloud/SaaS', 'AI/ML', 'Gaming', 'E-commerce'],
    majorVCs: ['Madrona Venture Group', 'Founder\'s Co-op', 'Trilogy Equity'],
    notableStartups: ['Outreach', 'Convoy', 'Rec Room', 'Highspot'],
    avgSeedRound: 2200000,
    avgSeriesA: 10000000,
  },
  {
    id: 'austin',
    name: 'Austin',
    city: 'Austin',
    country: 'United States',
    lat: 30.2672,
    lon: -97.7431,
    ecosystemTier: 'tier2',
    totalFunding2024: 8500000000,
    activeStartups: 3200,
    unicorns: 18,
    topSectors: ['AI/ML', 'Enterprise SaaS', 'Semiconductors', 'Cleantech'],
    majorVCs: ['LiveOak Venture Partners', 'S3 Ventures', 'Silverton Partners'],
    notableStartups: ['OpenAI Austin', 'Tesla AI', 'Jungle Scout', 'BigCommerce'],
    avgSeedRound: 2000000,
    avgSeriesA: 9000000,
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    city: 'Los Angeles',
    country: 'United States',
    lat: 34.0522,
    lon: -118.2437,
    ecosystemTier: 'tier2',
    totalFunding2024: 11000000000,
    activeStartups: 4100,
    unicorns: 24,
    topSectors: ['Entertainment Tech', 'AI/ML', 'Aerospace', 'Consumer'],
    majorVCs: ['Upfront Ventures', 'Crosscut Ventures', 'Mucker Capital'],
    notableStartups: ['SpaceX', 'Snap', 'Bird', 'Honeybook'],
    avgSeedRound: 2300000,
    avgSeriesA: 11000000,
  },

  // Europe
  {
    id: 'london',
    name: 'London',
    city: 'London',
    country: 'United Kingdom',
    lat: 51.5074,
    lon: -0.1278,
    ecosystemTier: 'tier1',
    totalFunding2024: 24000000000,
    activeStartups: 7500,
    unicorns: 38,
    topSectors: ['Fintech', 'AI/ML', 'Healthtech', 'Enterprise SaaS'],
    majorVCs: ['Index Ventures', 'Balderton Capital', 'Atomico', 'LocalGlobe'],
    notableStartups: ['DeepMind', 'Revolut', 'Monzo', 'Darktrace'],
    avgSeedRound: 1800000,
    avgSeriesA: 8000000,
  },
  {
    id: 'paris',
    name: 'Paris',
    city: 'Paris',
    country: 'France',
    lat: 48.8566,
    lon: 2.3522,
    ecosystemTier: 'tier2',
    totalFunding2024: 9500000000,
    activeStartups: 4200,
    unicorns: 26,
    topSectors: ['AI/ML', 'Deeptech', 'Fintech', 'Healthtech'],
    majorVCs: ['Partech', 'Eurazeo', 'Alven Capital', 'Elaia Partners'],
    notableStartups: ['Mistral AI', 'Qonto', 'Dataiku', 'Alan'],
    avgSeedRound: 1500000,
    avgSeriesA: 7000000,
  },
  {
    id: 'berlin',
    name: 'Berlin',
    city: 'Berlin',
    country: 'Germany',
    lat: 52.5200,
    lon: 13.4050,
    ecosystemTier: 'tier2',
    totalFunding2024: 7800000000,
    activeStartups: 3900,
    unicorns: 18,
    topSectors: ['Fintech', 'Enterprise SaaS', 'Mobility', 'AI/ML'],
    majorVCs: ['Earlybird', 'Cavalry Ventures', 'Target Global', 'HV Capital'],
    notableStartups: ['N26', 'Auto1', 'Tier Mobility', 'SoundCloud'],
    avgSeedRound: 1300000,
    avgSeriesA: 6000000,
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    lat: 52.3676,
    lon: 4.9041,
    ecosystemTier: 'tier2',
    totalFunding2024: 5200000000,
    activeStartups: 2800,
    unicorns: 14,
    topSectors: ['Fintech', 'SaaS', 'AI/ML', 'Logistics'],
    majorVCs: ['Inkef Capital', 'Peak Capital', 'Prosperity Capital'],
    notableStartups: ['Adyen', 'MessageBird', 'Mollie', 'Elastic'],
    avgSeedRound: 1200000,
    avgSeriesA: 5500000,
  },
  {
    id: 'stockholm',
    name: 'Stockholm',
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3293,
    lon: 18.0686,
    ecosystemTier: 'tier2',
    totalFunding2024: 4800000000,
    activeStartups: 2400,
    unicorns: 16,
    topSectors: ['Gaming', 'Fintech', 'SaaS', 'Cleantech'],
    majorVCs: ['EQT Ventures', 'Creandum', 'Northzone'],
    notableStartups: ['Spotify', 'Klarna', 'King', 'Northvolt'],
    avgSeedRound: 1400000,
    avgSeriesA: 6000000,
  },
  {
    id: 'zurich',
    name: 'Zurich',
    city: 'Zurich',
    country: 'Switzerland',
    lat: 47.3769,
    lon: 8.5417,
    ecosystemTier: 'tier2',
    totalFunding2024: 3500000000,
    activeStartups: 1800,
    unicorns: 9,
    topSectors: ['Deeptech', 'Fintech', 'AI/ML', 'Biotech'],
    majorVCs: ['Redalpine', 'btov Partners', 'Zühlke Ventures'],
    notableStartups: ['Scandit', 'GetYourGuide', 'On Running', 'MindMaze'],
    avgSeedRound: 1100000,
    avgSeriesA: 5000000,
  },

  // Asia-Pacific
  {
    id: 'beijing',
    name: 'Beijing',
    city: 'Beijing',
    country: 'China',
    lat: 39.9042,
    lon: 116.4074,
    ecosystemTier: 'tier1',
    totalFunding2024: 32000000000,
    activeStartups: 8900,
    unicorns: 54,
    topSectors: ['AI/ML', 'Enterprise Software', 'Fintech', 'Autonomous Driving'],
    majorVCs: ['Sequoia China', 'Matrix Partners China', 'GGV Capital', '5Y Capital'],
    notableStartups: ['ByteDance', 'Baidu AI', 'Megvii', 'Moonshot AI'],
    avgSeedRound: 2000000,
    avgSeriesA: 10000000,
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    city: 'Shanghai',
    country: 'China',
    lat: 31.2304,
    lon: 121.4737,
    ecosystemTier: 'tier1',
    totalFunding2024: 28000000000,
    activeStartups: 7200,
    unicorns: 42,
    topSectors: ['E-commerce', 'Fintech', 'AI/ML', 'Gaming'],
    majorVCs: ['Qiming Venture Partners', 'Gaorong Capital', 'Hillhouse Capital'],
    notableStartups: ['Pinduoduo', 'Xiaohongshu', 'miHoYo', 'Lufax'],
    avgSeedRound: 1800000,
    avgSeriesA: 9000000,
  },
  {
    id: 'shenzhen',
    name: 'Shenzhen',
    city: 'Shenzhen',
    country: 'China',
    lat: 22.5431,
    lon: 114.0579,
    ecosystemTier: 'tier1',
    totalFunding2024: 22000000000,
    activeStartups: 6800,
    unicorns: 36,
    topSectors: ['Hardware', 'AI/ML', 'Robotics', 'Consumer Electronics'],
    majorVCs: ['Shenzhen Capital Group', 'IDG Capital', 'Morningside Ventures'],
    notableStartups: ['DJI', 'Tencent', 'OnePlus', 'BYD'],
    avgSeedRound: 1600000,
    avgSeriesA: 8000000,
  },
  {
    id: 'singapore',
    name: 'Singapore',
    city: 'Singapore',
    country: 'Singapore',
    lat: 1.3521,
    lon: 103.8198,
    ecosystemTier: 'tier2',
    totalFunding2024: 11000000000,
    activeStartups: 4100,
    unicorns: 19,
    topSectors: ['Fintech', 'E-commerce', 'AI/ML', 'Logistics'],
    majorVCs: ['Vertex Ventures', 'East Ventures', 'Monk\'s Hill Ventures'],
    notableStartups: ['Grab', 'Sea Group', 'Razer', 'PatSnap'],
    avgSeedRound: 1500000,
    avgSeriesA: 7000000,
  },
  {
    id: 'bangalore',
    name: 'Bangalore',
    city: 'Bangalore',
    country: 'India',
    lat: 12.9716,
    lon: 77.5946,
    ecosystemTier: 'tier1',
    totalFunding2024: 14000000000,
    activeStartups: 6500,
    unicorns: 32,
    topSectors: ['SaaS', 'AI/ML', 'Fintech', 'E-commerce'],
    majorVCs: ['Accel India', 'Sequoia India', 'Blume Ventures', 'Lightspeed India'],
    notableStartups: ['Flipkart', 'Swiggy', 'Ola', 'Byju\'s'],
    avgSeedRound: 1200000,
    avgSeriesA: 6000000,
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.6762,
    lon: 139.6503,
    ecosystemTier: 'tier2',
    totalFunding2024: 6800000000,
    activeStartups: 3400,
    unicorns: 12,
    topSectors: ['AI/ML', 'Robotics', 'Gaming', 'Healthtech'],
    majorVCs: ['JAFCO', 'Global Brain', 'WiL', 'Incubate Fund'],
    notableStartups: ['Preferred Networks', 'SmartNews', 'Spiber', 'Mercari'],
    avgSeedRound: 1000000,
    avgSeriesA: 5000000,
  },
  {
    id: 'seoul',
    name: 'Seoul',
    city: 'Seoul',
    country: 'South Korea',
    lat: 37.5665,
    lon: 126.9780,
    ecosystemTier: 'tier2',
    totalFunding2024: 5200000000,
    activeStartups: 2900,
    unicorns: 14,
    topSectors: ['Gaming', 'AI/ML', 'E-commerce', 'Fintech'],
    majorVCs: ['Kakao Ventures', 'Softbank Ventures Asia', 'Korea Investment Partners'],
    notableStartups: ['Coupang', 'Krafton', 'Toss', 'Yanolja'],
    avgSeedRound: 900000,
    avgSeriesA: 4500000,
  },

  // Canada
  {
    id: 'toronto',
    name: 'Toronto',
    city: 'Toronto',
    country: 'Canada',
    lat: 43.6532,
    lon: -79.3832,
    ecosystemTier: 'tier2',
    totalFunding2024: 6200000000,
    activeStartups: 3100,
    unicorns: 16,
    topSectors: ['AI/ML', 'Fintech', 'Healthtech', 'Enterprise SaaS'],
    majorVCs: ['OMERS Ventures', 'Georgian Partners', 'iNovia Capital'],
    notableStartups: ['Cohere', 'Wealthsimple', 'Shopify (Ottawa)', 'Clearco'],
    avgSeedRound: 1600000,
    avgSeriesA: 7500000,
  },
  {
    id: 'montreal',
    name: 'Montreal',
    city: 'Montreal',
    country: 'Canada',
    lat: 45.5017,
    lon: -73.5673,
    ecosystemTier: 'tier2',
    totalFunding2024: 3800000000,
    activeStartups: 2200,
    unicorns: 8,
    topSectors: ['AI/ML', 'Gaming', 'Aerospace', 'Deeptech'],
    majorVCs: ['Real Ventures', 'Brightspark Ventures', 'iNovia Capital'],
    notableStartups: ['Element AI', 'Lightspeed Commerce', 'BrainBox AI', 'Hopper'],
    avgSeedRound: 1300000,
    avgSeriesA: 6000000,
  },

  // Israel
  {
    id: 'tel-aviv',
    name: 'Tel Aviv',
    city: 'Tel Aviv',
    country: 'Israel',
    lat: 32.0853,
    lon: 34.7818,
    ecosystemTier: 'tier1',
    totalFunding2024: 9200000000,
    activeStartups: 4800,
    unicorns: 24,
    topSectors: ['Cybersecurity', 'AI/ML', 'Fintech', 'Autonomous Systems'],
    majorVCs: ['Bessemer Venture Partners', 'Viola Ventures', 'Aleph', 'JVP'],
    notableStartups: ['Wiz', 'Snyk', 'Rapyd', 'Forter'],
    avgSeedRound: 1700000,
    avgSeriesA: 8000000,
  },

  // Australia
  {
    id: 'sydney',
    name: 'Sydney',
    city: 'Sydney',
    country: 'Australia',
    lat: -33.8688,
    lon: 151.2093,
    ecosystemTier: 'tier2',
    totalFunding2024: 3400000000,
    activeStartups: 2100,
    unicorns: 8,
    topSectors: ['Fintech', 'SaaS', 'Healthtech', 'AI/ML'],
    majorVCs: ['Blackbird Ventures', 'Square Peg Capital', 'AirTree Ventures'],
    notableStartups: ['Canva', 'Atlassian', 'AfterPay', 'Safety Culture'],
    avgSeedRound: 1100000,
    avgSeriesA: 5000000,
  },

  // Emerging Hubs
  {
    id: 'dubai',
    name: 'Dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    lat: 25.2048,
    lon: 55.2708,
    ecosystemTier: 'tier3',
    totalFunding2024: 2800000000,
    activeStartups: 1800,
    unicorns: 5,
    topSectors: ['Fintech', 'E-commerce', 'AI/ML', 'Logistics'],
    majorVCs: ['BECO Capital', 'Global Ventures', 'Wamda Capital'],
    notableStartups: ['Careem', 'Noon', 'Tabby', 'Anghami'],
    avgSeedRound: 1000000,
    avgSeriesA: 4500000,
  },
  {
    id: 'sao-paulo',
    name: 'São Paulo',
    city: 'São Paulo',
    country: 'Brazil',
    lat: -23.5505,
    lon: -46.6333,
    ecosystemTier: 'tier2',
    totalFunding2024: 4200000000,
    activeStartups: 2600,
    unicorns: 12,
    topSectors: ['Fintech', 'E-commerce', 'SaaS', 'Agtech'],
    majorVCs: ['Kaszek Ventures', 'Monashees', 'Valor Capital'],
    notableStartups: ['Nubank', 'Stone', 'QuintoAndar', 'Vtex'],
    avgSeedRound: 800000,
    avgSeriesA: 4000000,
  },

  // Additional Emerging Hubs
  {
    id: 'miami',
    name: 'Miami',
    city: 'Miami',
    country: 'United States',
    lat: 25.7617,
    lon: -80.1918,
    ecosystemTier: 'tier3',
    totalFunding2024: 3200000000,
    activeStartups: 1500,
    unicorns: 8,
    topSectors: ['Fintech', 'Crypto/Web3', 'Real Estate Tech', 'Healthcare'],
    majorVCs: ['Founders Fund Miami', 'a16z crypto', 'Atomic'],
    notableStartups: ['Blockchain.com', 'Pipe', 'Reef Technology', 'Papa'],
    avgSeedRound: 2000000,
    avgSeriesA: 8000000,
  },
  {
    id: 'denver',
    name: 'Denver/Boulder',
    city: 'Denver',
    country: 'United States',
    lat: 39.7392,
    lon: -104.9903,
    ecosystemTier: 'tier3',
    totalFunding2024: 4100000000,
    activeStartups: 2100,
    unicorns: 10,
    topSectors: ['Aerospace', 'Outdoor Tech', 'SaaS', 'Cleantech'],
    majorVCs: ['Foundry Group', 'Techstars', 'High Alpha'],
    notableStartups: ['Guild Education', 'Ibotta', 'Strava', 'SendGrid'],
    avgSeedRound: 1800000,
    avgSeriesA: 7500000,
  },
  {
    id: 'chicago',
    name: 'Chicago',
    city: 'Chicago',
    country: 'United States',
    lat: 41.8781,
    lon: -87.6298,
    ecosystemTier: 'tier3',
    totalFunding2024: 5500000000,
    activeStartups: 2800,
    unicorns: 14,
    topSectors: ['Fintech', 'Enterprise SaaS', 'Logistics', 'Foodtech'],
    majorVCs: ['MATH Venture Partners', 'Chicago Ventures', 'Lightbank'],
    notableStartups: ['Tempus', 'Relativity', 'Braintree', 'Grubhub'],
    avgSeedRound: 1500000,
    avgSeriesA: 6000000,
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    city: 'Barcelona',
    country: 'Spain',
    lat: 41.3851,
    lon: 2.1734,
    ecosystemTier: 'tier3',
    totalFunding2024: 2100000000,
    activeStartups: 1600,
    unicorns: 6,
    topSectors: ['Gaming', 'Fintech', 'Traveltech', 'Healthtech'],
    majorVCs: ['Nauta Capital', 'Seaya Ventures', 'Samaipata'],
    notableStartups: ['Glovo', 'Typeform', 'Factorial', 'Wallapop'],
    avgSeedRound: 900000,
    avgSeriesA: 4000000,
  },
  {
    id: 'helsinki',
    name: 'Helsinki',
    city: 'Helsinki',
    country: 'Finland',
    lat: 60.1699,
    lon: 24.9384,
    ecosystemTier: 'tier3',
    totalFunding2024: 2400000000,
    activeStartups: 1200,
    unicorns: 8,
    topSectors: ['Gaming', 'Cleantech', 'SaaS', 'Deeptech'],
    majorVCs: ['Lifeline Ventures', 'Maki.vc', 'Inventure'],
    notableStartups: ['Supercell', 'Wolt', 'Aiven', 'Relex'],
    avgSeedRound: 1100000,
    avgSeriesA: 4500000,
  },
  {
    id: 'munich',
    name: 'Munich',
    city: 'Munich',
    country: 'Germany',
    lat: 48.1351,
    lon: 11.5820,
    ecosystemTier: 'tier3',
    totalFunding2024: 3800000000,
    activeStartups: 2000,
    unicorns: 10,
    topSectors: ['Mobility', 'Enterprise AI', 'Deeptech', 'Industrialtech'],
    majorVCs: ['UVC Partners', 'TengelMann Ventures', 'Cherry Ventures'],
    notableStartups: ['Celonis', 'Personio', 'Lilium', 'FlixBus'],
    avgSeedRound: 1200000,
    avgSeriesA: 5500000,
  },
  {
    id: 'jakarta',
    name: 'Jakarta',
    city: 'Jakarta',
    country: 'Indonesia',
    lat: -6.2088,
    lon: 106.8456,
    ecosystemTier: 'tier2',
    totalFunding2024: 3600000000,
    activeStartups: 2500,
    unicorns: 8,
    topSectors: ['E-commerce', 'Fintech', 'Logistics', 'Edtech'],
    majorVCs: ['East Ventures', 'Alpha JWC Ventures', 'Sequoia India/SEA'],
    notableStartups: ['GoTo', 'Bukalapak', 'Traveloka', 'Xendit'],
    avgSeedRound: 700000,
    avgSeriesA: 3500000,
  },
  {
    id: 'lagos',
    name: 'Lagos',
    city: 'Lagos',
    country: 'Nigeria',
    lat: 6.5244,
    lon: 3.3792,
    ecosystemTier: 'tier3',
    totalFunding2024: 1800000000,
    activeStartups: 1100,
    unicorns: 5,
    topSectors: ['Fintech', 'Agtech', 'Logistics', 'Healthtech'],
    majorVCs: ['TLcom Capital', 'Partech Africa', '54 Collective'],
    notableStartups: ['Flutterwave', 'OPay', 'Andela', 'Paystack'],
    avgSeedRound: 600000,
    avgSeriesA: 2500000,
  },
  {
    id: 'nairobi',
    name: 'Nairobi',
    city: 'Nairobi',
    country: 'Kenya',
    lat: -1.2921,
    lon: 36.8219,
    ecosystemTier: 'tier3',
    totalFunding2024: 1200000000,
    activeStartups: 800,
    unicorns: 3,
    topSectors: ['Fintech', 'Agtech', 'Cleantech', 'Logistics'],
    majorVCs: ['Novastar Ventures', 'DOB Equity', 'Savannah Fund'],
    notableStartups: ['M-KOPA', 'Twiga Foods', 'Africa\'s Talking', 'Branch'],
    avgSeedRound: 500000,
    avgSeriesA: 2000000,
  },
  {
    id: 'mexico-city',
    name: 'Mexico City',
    city: 'Mexico City',
    country: 'Mexico',
    lat: 19.4326,
    lon: -99.1332,
    ecosystemTier: 'tier2',
    totalFunding2024: 2900000000,
    activeStartups: 1900,
    unicorns: 7,
    topSectors: ['Fintech', 'E-commerce', 'Logistics', 'Proptech'],
    majorVCs: ['ALLVP', 'Kaszek Ventures', 'QED Investors'],
    notableStartups: ['Kavak', 'Clip', 'Bitso', 'Konfio'],
    avgSeedRound: 700000,
    avgSeriesA: 3000000,
  },
  {
    id: 'ho-chi-minh',
    name: 'Ho Chi Minh City',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    lat: 10.8231,
    lon: 106.6297,
    ecosystemTier: 'tier3',
    totalFunding2024: 1100000000,
    activeStartups: 900,
    unicorns: 3,
    topSectors: ['Fintech', 'E-commerce', 'Edtech', 'Gaming'],
    majorVCs: ['VinaCapital Ventures', 'Do Ventures', '500 Startups Vietnam'],
    notableStartups: ['VNPay', 'Tiki', 'MoMo', 'Sky Mavis'],
    avgSeedRound: 400000,
    avgSeriesA: 1800000,
  },
];
