import type { TechCompany } from '@/types';

// Major technology companies and their key office locations
// Focused on AI, cloud, semiconductor, and major tech platforms

export const TECH_COMPANIES: TechCompany[] = [
  // AI Labs & Frontier Model Companies
  {
    id: 'openai-hq',
    name: 'OpenAI',
    sector: 'AI Research',
    officeType: 'headquarters',
    city: 'San Francisco',
    country: 'United States',
    lat: 37.7562,
    lon: -122.4193,
    employees: 700,
    foundedYear: 2015,
    keyProducts: ['GPT-4', 'ChatGPT', 'DALL-E', 'API Platform'],
    valuation: 80000000000, // $80B
  },
  {
    id: 'anthropic-hq',
    name: 'Anthropic',
    sector: 'AI Research',
    officeType: 'headquarters',
    city: 'San Francisco',
    country: 'United States',
    lat: 37.7937,
    lon: -122.3965,
    employees: 500,
    foundedYear: 2021,
    keyProducts: ['Claude', 'Constitutional AI'],
    valuation: 18400000000, // $18.4B
  },
  {
    id: 'google-deepmind-uk',
    name: 'Google DeepMind',
    sector: 'AI Research',
    officeType: 'headquarters',
    city: 'London',
    country: 'United Kingdom',
    lat: 51.5310,
    lon: -0.1247,
    employees: 2500,
    foundedYear: 2010,
    keyProducts: ['Gemini', 'AlphaGo', 'AlphaFold'],
  },
  {
    id: 'google-hq',
    name: 'Google/Alphabet',
    sector: 'Cloud/AI',
    officeType: 'headquarters',
    city: 'Mountain View',
    country: 'United States',
    lat: 37.4220,
    lon: -122.0841,
    employees: 182502,
    foundedYear: 1998,
    keyProducts: ['Search', 'Cloud', 'Gemini AI', 'YouTube'],
    stockSymbol: 'GOOGL',
    valuation: 2000000000000, // $2T
  },
  {
    id: 'meta-hq',
    name: 'Meta (Facebook)',
    sector: 'Social/AI',
    officeType: 'headquarters',
    city: 'Menlo Park',
    country: 'United States',
    lat: 37.4848,
    lon: -122.1482,
    employees: 67317,
    foundedYear: 2004,
    keyProducts: ['Facebook', 'Instagram', 'WhatsApp', 'Llama AI'],
    stockSymbol: 'META',
    valuation: 1200000000000, // $1.2T
  },
  {
    id: 'microsoft-hq',
    name: 'Microsoft',
    sector: 'Cloud/AI',
    officeType: 'headquarters',
    city: 'Redmond',
    country: 'United States',
    lat: 47.6423,
    lon: -122.1390,
    employees: 221000,
    foundedYear: 1975,
    keyProducts: ['Azure', 'Office 365', 'GitHub', 'OpenAI Investment'],
    stockSymbol: 'MSFT',
    valuation: 3000000000000, // $3T
  },
  {
    id: 'amazon-hq',
    name: 'Amazon',
    sector: 'Cloud/AI',
    officeType: 'headquarters',
    city: 'Seattle',
    country: 'United States',
    lat: 47.6223,
    lon: -122.3389,
    employees: 1541000,
    foundedYear: 1994,
    keyProducts: ['AWS', 'E-commerce', 'Alexa', 'Bedrock AI'],
    stockSymbol: 'AMZN',
    valuation: 1900000000000, // $1.9T
  },

  // Semiconductor / AI Chips
  {
    id: 'nvidia-hq',
    name: 'NVIDIA',
    sector: 'AI Chips',
    officeType: 'headquarters',
    city: 'Santa Clara',
    country: 'United States',
    lat: 37.3708,
    lon: -121.9646,
    employees: 29600,
    foundedYear: 1993,
    keyProducts: ['H100', 'A100', 'GB200', 'CUDA'],
    stockSymbol: 'NVDA',
    valuation: 3500000000000, // $3.5T
  },
  {
    id: 'amd-hq',
    name: 'AMD',
    sector: 'AI Chips',
    officeType: 'headquarters',
    city: 'Santa Clara',
    country: 'United States',
    lat: 37.3861,
    lon: -121.9633,
    employees: 26000,
    foundedYear: 1969,
    keyProducts: ['MI300X', 'EPYC', 'Ryzen'],
    stockSymbol: 'AMD',
  },
  {
    id: 'tsmc-hq',
    name: 'TSMC',
    sector: 'AI Chips',
    officeType: 'headquarters',
    city: 'Hsinchu',
    country: 'Taiwan',
    lat: 24.7799,
    lon: 121.0371,
    employees: 77000,
    foundedYear: 1987,
    keyProducts: ['3nm Process', '5nm Process', 'Chip Manufacturing'],
    stockSymbol: 'TSM',
    valuation: 900000000000, // $900B
  },

  // AI Startups
  {
    id: 'mistral-hq',
    name: 'Mistral AI',
    sector: 'AI Research',
    officeType: 'headquarters',
    city: 'Paris',
    country: 'France',
    lat: 48.8566,
    lon: 2.3522,
    employees: 240,
    foundedYear: 2023,
    keyProducts: ['Mistral Large', 'Mixtral'],
    valuation: 6000000000, // $6B
  },
  {
    id: 'cohere-hq',
    name: 'Cohere',
    sector: 'AI Research',
    officeType: 'headquarters',
    city: 'Toronto',
    country: 'Canada',
    lat: 43.6532,
    lon: -79.3832,
    employees: 400,
    foundedYear: 2019,
    keyProducts: ['Command', 'Embed', 'Rerank'],
    valuation: 5000000000, // $5B
  },
  {
    id: 'inflection-hq',
    name: 'Inflection AI',
    sector: 'AI Research',
    officeType: 'headquarters',
    city: 'Palo Alto',
    country: 'United States',
    lat: 37.4419,
    lon: -122.1430,
    employees: 35,
    foundedYear: 2022,
    keyProducts: ['Pi Assistant'],
    valuation: 4000000000, // $4B
  },
  {
    id: 'adept-hq',
    name: 'Adept AI',
    sector: 'AI Research',
    officeType: 'headquarters',
    city: 'San Francisco',
    country: 'United States',
    lat: 37.7749,
    lon: -122.4194,
    employees: 50,
    foundedYear: 2022,
    keyProducts: ['ACT-1', 'AI Automation'],
    valuation: 1000000000, // $1B
  },
  {
    id: 'perplexity-hq',
    name: 'Perplexity AI',
    sector: 'AI Research',
    officeType: 'headquarters',
    city: 'San Francisco',
    country: 'United States',
    lat: 37.7749,
    lon: -122.4194,
    employees: 80,
    foundedYear: 2022,
    keyProducts: ['AI Search'],
    valuation: 9000000000, // $9B
  },

  // Chinese AI Companies
  {
    id: 'baidu-hq',
    name: 'Baidu',
    sector: 'AI Research',
    officeType: 'headquarters',
    city: 'Beijing',
    country: 'China',
    lat: 39.9925,
    lon: 116.3272,
    employees: 36000,
    foundedYear: 2000,
    keyProducts: ['ERNIE Bot', 'Search', 'Apollo'],
    stockSymbol: 'BIDU',
  },
  {
    id: 'bytedance-hq',
    name: 'ByteDance',
    sector: 'Social/AI',
    officeType: 'headquarters',
    city: 'Beijing',
    country: 'China',
    lat: 39.9163,
    lon: 116.4896,
    employees: 150000,
    foundedYear: 2012,
    keyProducts: ['TikTok', 'Douyin', 'AI Recommendations'],
    valuation: 225000000000, // $225B
  },
  {
    id: 'alibaba-hq',
    name: 'Alibaba Cloud',
    sector: 'Cloud/AI',
    officeType: 'headquarters',
    city: 'Hangzhou',
    country: 'China',
    lat: 30.2741,
    lon: 120.1551,
    employees: 239000,
    foundedYear: 1999,
    keyProducts: ['Alibaba Cloud', 'Tongyi Qianwen', 'E-commerce'],
    stockSymbol: 'BABA',
  },
  {
    id: 'tencent-hq',
    name: 'Tencent',
    sector: 'Cloud/AI',
    officeType: 'headquarters',
    city: 'Shenzhen',
    country: 'China',
    lat: 22.5431,
    lon: 114.0579,
    employees: 105000,
    foundedYear: 1998,
    keyProducts: ['WeChat', 'Tencent Cloud', 'Gaming'],
  },
  {
    id: 'moonshot-hq',
    name: 'Moonshot AI',
    sector: 'AI Research',
    officeType: 'headquarters',
    city: 'Beijing',
    country: 'China',
    lat: 39.9042,
    lon: 116.4074,
    employees: 200,
    foundedYear: 2023,
    keyProducts: ['Kimi Chat'],
    valuation: 2500000000, // $2.5B
  },

  // Enterprise AI
  {
    id: 'databricks-hq',
    name: 'Databricks',
    sector: 'AI Platform',
    officeType: 'headquarters',
    city: 'San Francisco',
    country: 'United States',
    lat: 37.7749,
    lon: -122.4194,
    employees: 5500,
    foundedYear: 2013,
    keyProducts: ['Lakehouse', 'MLOps', 'DBRX'],
    valuation: 43000000000, // $43B
  },
  {
    id: 'scale-ai-hq',
    name: 'Scale AI',
    sector: 'AI Data',
    officeType: 'headquarters',
    city: 'San Francisco',
    country: 'United States',
    lat: 37.7749,
    lon: -122.4194,
    employees: 600,
    foundedYear: 2016,
    keyProducts: ['Data Labeling', 'Foundation Model Platforms'],
    valuation: 14000000000, // $14B
  },
  {
    id: 'huggingface-hq',
    name: 'Hugging Face',
    sector: 'AI Platform',
    officeType: 'headquarters',
    city: 'New York',
    country: 'United States',
    lat: 40.7128,
    lon: -74.0060,
    employees: 400,
    foundedYear: 2016,
    keyProducts: ['Model Hub', 'Transformers', 'Inference'],
    valuation: 4500000000, // $4.5B
  },

  // AI Hardware Startups
  {
    id: 'cerebras-hq',
    name: 'Cerebras',
    sector: 'AI Chips',
    officeType: 'headquarters',
    city: 'Sunnyvale',
    country: 'United States',
    lat: 37.3688,
    lon: -122.0363,
    employees: 400,
    foundedYear: 2016,
    keyProducts: ['CS-2', 'Wafer-Scale Engine'],
    stockSymbol: 'CBRS',
  },
  {
    id: 'groq-hq',
    name: 'Groq',
    sector: 'AI Chips',
    officeType: 'headquarters',
    city: 'Mountain View',
    country: 'United States',
    lat: 37.3861,
    lon: -122.0839,
    employees: 350,
    foundedYear: 2016,
    keyProducts: ['LPU', 'Inference Chips'],
    valuation: 2800000000, // $2.8B
  },
  {
    id: 'sambanova-hq',
    name: 'SambaNova Systems',
    sector: 'AI Chips',
    officeType: 'headquarters',
    city: 'Palo Alto',
    country: 'United States',
    lat: 37.4419,
    lon: -122.1430,
    employees: 600,
    foundedYear: 2017,
    keyProducts: ['DataScale', 'RDU Chips'],
    valuation: 5000000000, // $5B
  },

  // European Tech
  {
    id: 'sap-hq',
    name: 'SAP',
    sector: 'Enterprise/AI',
    officeType: 'headquarters',
    city: 'Walldorf',
    country: 'Germany',
    lat: 49.3044,
    lon: 8.6434,
    employees: 105000,
    foundedYear: 1972,
    keyProducts: ['ERP', 'SAP AI', 'Cloud'],
    stockSymbol: 'SAP',
  },
  {
    id: 'spotify-hq',
    name: 'Spotify',
    sector: 'Media/AI',
    officeType: 'headquarters',
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3293,
    lon: 18.0686,
    employees: 9800,
    foundedYear: 2006,
    keyProducts: ['Music Streaming', 'AI Recommendations'],
    stockSymbol: 'SPOT',
  },

  // Key Regional Offices
  {
    id: 'google-london',
    name: 'Google London',
    sector: 'Cloud/AI',
    officeType: 'major office',
    city: 'London',
    country: 'United Kingdom',
    lat: 51.5339,
    lon: -0.1247,
    employees: 7000,
    foundedYear: 2003,
    keyProducts: ['European HQ'],
  },
  {
    id: 'meta-london',
    name: 'Meta London',
    sector: 'Social/AI',
    officeType: 'major office',
    city: 'London',
    country: 'United Kingdom',
    lat: 51.5074,
    lon: -0.0901,
    employees: 5000,
    foundedYear: 2007,
    keyProducts: ['European Engineering Hub'],
  },
  {
    id: 'amazon-berlin',
    name: 'Amazon Berlin',
    sector: 'Cloud/AI',
    officeType: 'major office',
    city: 'Berlin',
    country: 'Germany',
    lat: 52.5200,
    lon: 13.4050,
    employees: 3500,
    foundedYear: 2013,
    keyProducts: ['AWS Europe'],
  },
  {
    id: 'apple-singapore',
    name: 'Apple Singapore',
    sector: 'Consumer/AI',
    officeType: 'major office',
    city: 'Singapore',
    country: 'Singapore',
    lat: 1.2789,
    lon: 103.8489,
    employees: 2000,
    foundedYear: 1981,
    keyProducts: ['APAC Operations'],
  },
];
